let vinnie = document.querySelector("#vinnie")
let tarragon = document.querySelector("#tarragon")
let canariP = document.querySelector("#canari1")
let canariE = document.querySelector("#canari2")
let gwynnE = document.querySelector("#gwynn1")
let ivorP = document.querySelector("#ivor1")
let philippeD = document.querySelector("#philippe1")
let gwynnD = document.querySelector("#gwynn2")
let corbeauP = document.querySelector("#corbeau1")
// let lida = document.querySelector("#lida")
let naveen = document.querySelector("#naveen")
let lebanne = document.querySelector("#lebanne")
let canariT = document.querySelector("#canari3")
let ivorT = document.querySelector("#ivor2")
let corbeauT = document.querySelector("#corbeau2")
let jacinthe = document.querySelector("#jacinthe")
let philippeB = document.querySelector("#philippe2")
let emma = document.querySelector("#emma")
let griselle = document.querySelector("#griselle")
let grisham = document.querySelector("#grisham")
let urbainTaunieCM = document.querySelector("#urbain_taunie1")
let urbainTaunieCE = document.querySelector("#urbain_taunie2")
let urbainTaunieCF = document.querySelector("#urbain_taunie3")
let lPostgame = document.querySelector("#l")

let za_trainers = [
    {
        namea : "Houndoom",
        levela : "LV: 30",
        typea : "Type: Dark/Fire",
        abilitya: "Ability: N/AN/A",
        itema : "Item: None",
        hpa : "HP: 85",
        atka : "Atk: 59",
        defa : "Def: 35",
        spatka : "Sp. Atk: 71",
        spdefa : "Sp. Def: 53",
        spda : "Spd: 62",
        move1a : "-Fire Fang",
        move2a : "-Fire Spin",
        move3a : "-Bite",
        move4a : "-Roar",

        nameb : "Sharpedo",
        levelb : "LV: 30",
        typeb : "Type: Water/Dark",
        abilityb: "Ability: N/A",
        itemb : "Item: None",
        hpb : "HP: 100",
        atkb : "Atk: 77",
        defb : "Def: 29",
        spatkb : "Sp. Atk: 62",
        spdefb : "Sp. Def: 29",
        spdb : "Spd: 62",
        move1b : "-Whirlpool",
        move2b : "-Aqua Jet",
        move3b : "-Night Slash",
        move4b : "-Slash",

        namec : "Buneary",
        levelc : "LV: 30",
        typec : "Type: Normal",
        abilityc: "Ability: N/A",
        itemc : "Item: None",
        hpc : "HP: 91",
        atkc : "Atk: 44",
        defc : "Def: 31",
        spatkc : "Sp. Atk: 31",
        spdefc : "Sp. Def: 38",
        spdc : "Spd: 56",
        move1c : "-Charm",
        move2c : "-Quick Attack",
        move3c : "-Draining Kiss",
        move4c : "=Brutal Swing",

        named : "Mega Drampa",
        leveld : "LV: 32",
        typed : "Type: Normal/Dragon",
        abilityd: "Ability: N/A",
        itemd : "Item: Drampanite",
        hpd : "HP: 116",
        atkd : "Atk: 64",
        defd : "Def: 80",
        spatkd : "Sp. Atk: 112",
        spdefd : "Sp. Def: 84",
        spdd : "Spd: 32",
        move1d : "-Safeguard",
        move2d : "-Icy Wind",
        move3d : "-Twister",
        move4d : "-Glare",
    },

    {
        namea : "Hippowdon",
        levela : "LV: 36",
        typea : "Type: Ground",
        abilitya: "Ability: N/A",
        itema : "Item: None",
        hpa : "HP: 146",
        atka : "Atk: 85",
        defa : "Def: 89",
        spatka : "Sp. Atk: 53",
        spdefa : "Sp. Def: 56",
        spda : "Spd: 38",
        move1a : "-Heavy Slam",
        move2a : "-Amnesia",
        move3a : "-Crunch",
        move4a : "-Stealth Rock",

        nameb : "Diggersby",
        levelb : "LV: 36",
        typeb : "Type: Normal/Ground",
        abilityb: "Ability: N/A",
        itemb : "Item: None",
        hpb : "HP: 129",
        atkb : "Atk: 45",
        defb : "Def: 60",
        spatkb : "Sp. Atk: 41",
        spdefb : "Sp. Def: 60",
        spdb : "Spd: 61",
        move1b : "-Swords Dance",
        move2b : "-Take Down",
        move3b : "-Bounce",
        move4b : "-Bulldoze",

        namec : "Mega Excadrill",
        levelc : "LV: 37",
        typec : "Type: Ground/Steel",
        abilityc: "Ability: N/A",
        itemc : "Item: Excadrite",
        hpc : "HP: 157",
        atkc : "Atk: 132",
        defc : "Def: 84",
        spatkc : "Sp. Atk: 58",
        spdefc : "Sp. Def: 58",
        spdc : "Spd: 86",
        move1c : "-Swords Dance",
        move2c : "-Dig",
        move3c : "-Rock Slide",
        move4c : "-X-Scissor",
    },

    {
        namea : "Heliolisk",
        levela : "LV: 37",
        typea : "Type: Electric/Normal",
        abilitya: "Ability: N/A",
        itema : "Item: None",
        hpa : "HP: 116",
        atka : "Atk: 45",
        defa : "Def: 43",
        spatka : "Sp. Atk: 85",
        spdefa : "Sp. Def: 74",
        spda : "Spd: 85",
        move1a : "-Swift",
        move2a : "-Parabolic Charge",
        move3a : "-Volt Switch",
        move4a : "-Bulldoze",

        nameb : "Ampharos",
        levelb : "LV: 38",
        typeb : "Type: Electric",
        abilityb: "Ability: N/A",
        itemb : "Item: None",
        hpb : "HP: 140",
        atkb : "Atk: 62",
        defb : "Def: 69",
        spatkb : "Sp. Atk: 92",
        spdefb : "Sp. Def: 73",
        spdb : "Spd: 46",
        move1b : "-Cotton Guard",
        move2b : "-Discharge",
        move3b : "-Power Gem",
        move4b : "-Dragon Pulse",

        namec : "Stunfisk",
        levelc : "LV: 38",
        typec : "Type: Ground/Electric",
        abilityc: "Ability: N/A",
        itemc : "Item: None",
        hpc : "HP: 154",
        atkc : "Atk: 55",
        defc : "Def: 68",
        spatkc : "Sp. Atk: 66",
        spdefc : "Sp. Def: 80",
        spdc : "Spd: 29",
        move1c : "-Discharge",
        move2c : "-Spark",
        move3c : "-Charge",
        move4c : "-Mud Shot",

        named : "Mega Eelektross",
        leveld : "LV: 39",
        typed : "Type: Electric",
        abilityd: "Ability: N/A",
        itemd : "Item: Eelektrossite",
        hpd : "HP: 145",
        atkd : "Atk: 123",
        defd : "Def: 73",
        spatkd : "Sp. Atk: 116",
        spdefd : "Sp. Def: 81",
        spdd : "Spd: 73",
        move1d : "-Discharge",
        move2d : "-Crunch",
        move3d : "-Volt Switch",
        move4d : "-Eerie Impulse",
    },

    {
        namea : "Heliolisk",
        levela : "LV: 42",
        typea : "Type: Electric/Normal",
        abilitya: "Ability: N/A",
        itema : "Item: None",
        hpa : "HP: 130",
        atka : "Atk: 51",
        defa : "Def: 48",
        spatka : "Sp. Atk: 96",
        spdefa : "Sp. Def: 83",
        spda : "Spd: 96",
        move1a : "-Thunder Wave",
        move2a : "-Parabolic Charge",
        move3a : "-Thunderbolt",
        move4a : "-Bulldoze",

        nameb : "Ampharos",
        levelb : "LV: 43",
        typeb : "Type: Electric",
        abilityb: "Ability: N/A",
        itemb : "Item: None",
        hpb : "HP: 157",
        atkb : "Atk: 69",
        defb : "Def: 78",
        spatkb : "Sp. Atk: 103",
        spdefb : "Sp. Def: 82",
        spdb : "Spd: 52",
        move1b : "-Dazzling Gleam",
        move2b : "-Discharge",
        move3b : "-Power Gem",
        move4b : "-Ice Punch",

        namec : "Stunfisk",
        levelc : "LV: 43",
        typec : "Type: Ground/Electric",
        abilityc: "Ability: N/A",
        itemc : "Item: None",
        hpc : "HP: 173",
        atkc : "Atk: 61",
        defc : "Def: 77",
        spatkc : "Sp. Atk: 74",
        spdefc : "Sp. Def: 90",
        spdc : "Spd: 32",
        move1c : "-Discharge",
        move2c : "-Thunder Shock",
        move3c : "-Stealth Rock",
        move4c : "-Mud Shot",

        named : "Mega Eelektross",
        leveld : "LV: 44",
        typed : "Type: Electric",
        abilityd: "Ability: N/A",
        itemd : "Item: Eelektrossite",
        hpd : "HP: 163",
        atkd : "Atk: 139",
        defd : "Def: 82",
        spatkd : "Sp. Atk: 130",
        spdefd : "Sp. Def: 90",
        spdd : "Spd: 82",
        move1d : "-Discharge",
        move2d : "-Fire Punch",
        move3d : "-Volt Switch",
        move4d : "-Giga Drain",
    },

    {
        namea : "Banette",
        levela : "LV: 43",
        typea : "Type: Ghost",
        abilitya: "Ability: N/A",
        itema : "Item: None",
        hpa : "HP: 135",
        atka : "Atk: 103",
        defa : "Def: 60",
        spatka : "Sp. Atk: 76",
        spdefa : "Sp. Def: 59",
        spda : "Spd: 60",
        move1a : "-Shadow Sneak",
        move2a : "-Shadow Claw",
        move3a : "-Knock Off",
        move4a : "-Heal Block",

        nameb : "Gourgeist (Small)",
        levelb : "LV: 44",
        typeb : "Type: Ghost/Grass",
        abilityb: "Ability: N/A",
        itemb : "Item: None",
        hpb : "HP: 130",
        atkb : "Atk: 79",
        defb : "Def: 112",
        spatkb : "Sp. Atk: 56",
        spdefb : "Sp. Def: 71",
        spdb : "Spd: 92",
        move1b : "-Trick-or-Treat",
        move2b : "-Shadow Claw",
        move3b : "-Bullet Seed",
        move4b : "-Brutal Swing",

        namec : "Mega Chandelure",
        levelc : "LV: 45",
        typec : "Type: Ghost/Fire",
        abilityc: "Ability: N/A",
        itemc : "Item: Chandelurite",
        hpc : "HP: 144",
        atkc : "Atk: 79",
        defc : "Def: 110",
        spatkc : "Sp. Atk: 169",
        spdefc : "Sp. Def: 110",
        spdc : "Spd: 92",
        move1c : "-Flamethrower",
        move2c : "-Shadow Ball",
        move3c : "-Fire Spin",
        move4c : "-Protect",
    },

    {
        namea : "Heracross",
        levela : "LV: 45",
        typea : "Type: Bug/Fighting",
        abilitya: "Ability: N/A",
        itema : "Item: None",
        hpa : "HP: 155",
        atka : "Atk: 117",
        defa : "Def: 72",
        spatka : "Sp. Atk: 41",
        spdefa : "Sp. Def: 90",
        spda : "Spd: 81",
        move1a : "-Rock Blast",
        move2a : "-Pin Missile",
        move3a : "-Aerial Ace",
        move4a : "-Brick Break",

        nameb : "Medicham",
        levelb : "LV: 46",
        typeb : "Type: Fighting/Psychic",
        abilityb: "Ability: N/A",
        itemb : "Item: None",
        hpb : "HP: 140",
        atkb : "Atk: U/A",
        defb : "Def: 74",
        spatkb : "Sp. Atk: 60",
        spdefb : "Sp. Def: 74",
        spdb : "Spd: 78",
        move1b : "-Zen Headbutt",
        move2b : "-Rock Smash",
        move3b : "-Protect",
        move4b : "-Ice Punch",

        namec : "Machamp",
        levelc : "LV: 46",
        typec : "Type: Fighting",
        abilityc: "Ability: N/A",
        itemc : "Item: None",
        hpc : "HP: 167",
        atkc : "Atk: 124",
        defc : "Def: 78",
        spatkc : "Sp. Atk: 64",
        spdefc : "Sp. Def: 83",
        spdc : "Spd: 55",
        move1c : "-Bulldoze",
        move2c : "-Brick Break",
        move3c : "-Bulk Up",
        move4c : "-Brutal Swing",

        named : "Mega Falinks",
        leveld : "LV: 47",
        typed : "Type: Fighting",
        abilityd: "Ability: N/A",
        itemd : "Item: Falinksite",
        hpd : "HP: 154",
        atkd : "Atk: 138",
        defd : "Def: 138",
        spatkd : "Sp. Atk: 77",
        spdefd : "Sp. Def: 73",
        spdd : "Spd: 106",
        move1d : "-Iron Head",
        move2d : "-No Retreat",
        move3d : "-Rock Slide",
        move4d : "-Brick Break",
    },

    {
        namea : "Steelix",
        levela : "LV: 46",
        typea : "Type: Steel/Ground",
        abilitya: "Ability: N/A",
        itema : "Item: None",
        hpa : "HP: 153",
        atka : "Atk: 83",
        defa : "Def: 189",
        spatka : "Sp. Atk: 55",
        spdefa : "Sp. Def: 64",
        spda : "Spd: 32",
        move1a : "-Stealth Rock",
        move2a : "-Heavy Slam",
        move3a : "-Crunch",
        move4a : "-Rock Slide",

        nameb : "Scizor",
        levelb : "LV: 46",
        typeb : "Type: Bug/Steel",
        abilityb: "Ability: N/A",
        itemb : "Item: None",
        hpb : "HP: 149",
        atkb : "Atk: 124",
        defb : "Def: 97",
        spatkb : "Sp. Atk: 55",
        spdefb : "Sp. Def: 78",
        spdb : "Spd: 64",
        move1b : "-X-Scissor",
        move2b : "-Air Slash",
        move3b : "-Swords Dance",
        move4b : "-Bullet Punch",

        namec : "Mega Skarmory",
        levelc : "LV: 47",
        typec : "Type: Steel/Flying",
        abilityc: "Ability: N/A",
        itemc : "Item: Skarmorite",
        hpc : "HP: 154",
        atkc : "Atk: 143",
        defc : "Def: 115",
        spatkc : "Sp. Atk: 49",
        spdefc : "Sp. Def: 106",
        spdc : "Spd: 115",
        move1c : "-Steel Wing",
        move2c : "-Drill Run",
        move3c : "-Night Slash",
        move4c : "-Air Slash",
    },

    {
        namea : "Banette",
        levela : "LV: 45",
        typea : "Type: Ghost",
        abilitya: "Ability: N/A",
        itema : "Item: None",
        hpa : "HP: 140",
        atka : "Atk: 108",
        defa : "Def: 63",
        spatka : "Sp. Atk: 79",
        spdefa : "Sp. Def: 61",
        spda : "Spd: 63",
        move1a : "-Phantom Force",
        move2a : "-Shadow Claw",
        move3a : "-Knock Off",
        move4a : "-Heal Block",

        nameb : "Gourgeist (Small)",
        levelb : "LV: 46",
        typeb : "Type: Ghost/Grass",
        abilityb: "Ability: N/A",
        itemb : "Item: None",
        hpb : "HP: 135",
        atkb : "Atk: 83",
        defb : "Def: 117",
        spatkb : "Sp. Atk: 58",
        spdefb : "Sp. Def: 74",
        spdb : "Spd: 96",
        move1b : "-Trick-or-Treat",
        move2b : "-Shadow Claw",
        move3b : "-Bullet Seed",
        move4b : "-Brutal Swing",

        namec : "Gengar",
        levelc : "LV: 46",
        typec : "Type: Ghost/Poison",
        abilityc: "Ability: N/A",
        itemc : "Item: None",
        hpc : "HP: 140",
        atkc : "Atk: 64",
        defc : "Def: 60",
        spatkc : "Sp. Atk: 124",
        spdefc : "Sp. Def: 74",
        spdc : "Spd: 106",
        move1c : "-Shadow Ball",
        move2c : "-Icy Wind",
        move3c : "-Dark Pulse",
        move4c : "-Hypnosis",

        named : "Mega Chandelure",
        leveld : "LV: 47",
        typed : "Type: Ghost/Fire",
        abilityd: "Ability: N/A",
        itemd : "Item: Chandelurite",
        hpd : "HP: 150",
        atkd : "Atk: 82",
        defd : "Def: 115",
        spatkd : "Sp. Atk: 176",
        spdefd : "Sp. Def: 115",
        spdd : "Spd: 96",
        move1d : "-Flamethrower",
        move2d : "-Shadow Ball",
        move3d : "-Psychic",
        move4d : "-Calm Mind",
    },

    {
        namea : "Arbok",
        levela : "LV: 50",
        typea : "Type: Poison",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 151",
        atka : "Atk: 100",
        defa : "Def: 74",
        spatka : "Sp. Atk: 70",
        spdefa : "Sp. Def: 84",
        spda : "Spd: 85",
        move1a : "-Poison Jab",
        move2a : "-Toxic",
        move3a : "-Fire Fang",
        move4a : "-Leech Life",

        nameb : "Gyarados",
        levelb : "LV: 51",
        typeb : "Type: Water/Flying",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 190",
        atkb : "Atk: 132",
        defb : "Def: 85",
        spatkb : "Sp. Atk: 66",
        spdefb : "Sp. Def: 107",
        spdb : "Spd: 87",
        move1b : "-Waterfall",
        move2b : "-Bounce",
        move3b : "-Dragon Rush",
        move4b : "-Crunch",

        namec : "Roserade",
        levelc : "LV: 51",
        typec : "Type: Grass/Poison",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 154",
        atkc : "Atk: 76",
        defc : "Def: 71",
        spatkc : "Sp. Atk: 132",
        spdefc : "Sp. Def: 112",
        spdc : "Spd: 96",
        move1c : "-Giga Drain",
        move2c : "-Sludge Bomb",
        move3c : "-Synthesis",
        move4c : "-Shadow Ball",

        named : "Mega Scolipede",
        leveld : "LV: 52",
        typed : "Type: Bug/Poison",
        abilityd: "Ability: ",
        itemd : "Item: Scolipite",
        hpd : "HP: 164",
        atkd : "Atk: 158",
        defd : "Def: 167",
        spatkd : "Sp. Atk: 90",
        spdefd : "Sp. Def: 115",
        spdd : "Spd: 77",
        move1d : "-X-Scissor",
        move2d : "-Gunk Shot",
        move3d : "-Protect",
        move4d : "-Earthquake",
    },

    {
        namea : "Clawitzer",
        levela : "LV: 46",
        typea : "Type: Water",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 121",
        atka : "Atk: 72",
        defa : "Def: 85",
        spatka : "Sp. Atk: 115",
        spdefa : "Sp. Def: 86",
        spda : "Spd: 59",
        move1a : "-Water Pulse",
        move2a : "-Dark Pulse",
        move3a : "-Aura Sphere",
        move4a : "-Mud Shot",

        nameb : "Vanillish",
        levelb : "LV: 46",
        typeb : "Type: Ice",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 102",
        atkb : "Atk: 64",
        defb : "Def: 64",
        spatkb : "Sp. Atk: 78",
        spdefb : "Sp. Def: 74",
        spdb : "Spd: 59",
        move1b : "-Ice Beam",
        move2b : "-Icy Wind",
        move3b : "-Icicle Crash",
        move4b : "-Flash Cannon",

        namec : "Emolga",
        levelc : "LV: 47",
        typec : "Type: Electric/Flying",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 108",
        atkc : "Atk: 75",
        defc : "Def: 61",
        spatkc : "Sp. Atk: 75",
        spdefc : "Sp. Def: 61",
        spdc : "Spd: 101",
        move1c : "-Volt Switch",
        move2c : "-Air Slash",
        move3c : "-Spark",
        move4c : "-Quick Attack",

        named : "Staryu",
        leveld : "LV: 48",
        typed : "Type: Water",
        abilityd: "Ability: ",
        itemd : "Item: None",
        hpd : "HP: 86",
        atkd : "Atk: 48",
        defd : "Def: 57",
        spatkd : "Sp. Atk: 72",
        spdefd : "Sp. Def: 57",
        spdd : "Spd: 86",
        move1d : "-Surf",
        move2d : "-Power Gem",
        move3d : "-Psychic",
        move4d : "-Swift",
    },

    {
        namea : "Ariados",
        levela : "LV: 48",
        typea : "Type: Bug/Poison",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 125",
        atka : "Atk: 91",
        defa : "Def: 72",
        spatka : "Sp. Atk: 62",
        spdefa : "Sp. Def: 72",
        spda : "Spd: 43",
        move1a : "-Megahorn",
        move2a : "-Sticky Web",
        move3a : "-Leech Life",
        move4a : "-Poison Jab",

        nameb : "Sableye",
        levelb : "LV: 48",
        typeb : "Type: Dark/Ghost",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 106",
        atkb : "Atk: 77",
        defb : "Def: 77",
        spatkb : "Sp. Atk: 67",
        spdefb : "Sp. Def: 67",
        spdb : "Spd: 53",
        move1b : "-Shadow Claw",
        move2b : "-Zen Headbutt",
        move3b : "-Confuse Ray",
        move4b : "-Power Gem",

        namec : "Krookodile",
        levelc : "LV: 49",
        typec : "Type: Ground/Dark",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 152",
        atkc : "Atk: 119",
        defc : "Def: 83",
        spatkc : "Sp. Atk: 68",
        spdefc : "Sp. Def: 73",
        spdc : "Spd: 95",
        move1c : "-Earthquake",
        move2c : "-Sand Tomb",
        move3c : "-Crunch",
        move4c : "-Iron Tail",

        named : "Mega Scrafty",
        leveld : "LV: 50",
        typed : "Type: Dark/Fighting",
        abilityd: "Ability: ",
        itemd : "Item: Scraftinite",
        hpd : "HP: 125",
        atkd : "Atk: 135",
        defd : "Def: 140",
        spatkd : "Sp. Atk: 60",
        spdefd : "Sp. Def: 140",
        spdd : "Spd: 73",
        move1d : "-Power-Up Punch",
        move2d : "-Crunch",
        move3d : "-Iron Tail",
        move4d : "-Ice Punch",
    },

    {
        namea : "Noivern",
        levela : "LV: 53",
        typea : "Type: Flying/Dragon",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 186",
        atka : "Atk: 79",
        defa : "Def: 89",
        spatka : "Sp. Atk: 107",
        spdefa : "Sp. Def: 89",
        spda : "Spd: 135",
        move1a : "-Dragon Pulse",
        move2a : "-Air Slash",
        move3a : "-Hurricane",
        move4a : "-Super Fang",

        nameb : "Tyrantrum",
        levelb : "LV: 53",
        typeb : "Type: Rock/Dragon",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 183",
        atkb : "Atk: 133",
        defb : "Def: 131",
        spatkb : "Sp. Atk: 78",
        spdefb : "Sp. Def: 67",
        spdb : "Spd: 80",
        move1b : "-Rock Slide",
        move2b : "-Breaking Swipe",
        move3b : "-Crunch",
        move4b : "-Earthquake",

        namec : "Garchomp",
        levelc : "LV: 53",
        typec : "Type: Dragon/Ground",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 210",
        atkc : "Atk: 142",
        defc : "Def: 105",
        spatkc : "Sp. Atk: 89",
        spdefc : "Sp. Def: 95",
        spdc : "Spd: 113",
        move1c : "-Swords Dance",
        move2c : "-Earthquake",
        move3c : "-Dragon Claw",
        move4c : "-Iron Head",

        named : "Mega Dragalge",
        leveld : "LV: 54",
        typed : "Type: Poison/Dragon",
        abilityd: "Ability: ",
        itemd : "Item: Dragalgite",
        hpd : "HP: 176",
        atkd : "Atk: 104",
        defd : "Def: 126",
        spatkd : "Sp. Atk: 155",
        spdefd : "Sp. Def: 189",
        spdd : "Spd: 60",
        move1d : "-Hydro Pump",
        move2d : "-Dragon Pulse",
        move3d : "-Sludge Bomb",
        move4d : "-Protect",
    },

    {
        namea : "Heliolisk",
        levela : "LV: 53",
        typea : "Type: Electric/Normal",
        abilitya: "Ability: N/A",
        itema : "Item: None",
        hpa : "HP: 162",
        atka : "Atk: 63",
        defa : "Def: 60",
        spatka : "Sp. Atk: 120",
        spdefa : "Sp. Def: 104",
        spda : "Spd: 120",
        move1a : "-Thunder Wave",
        move2a : "-Parabolic Charge",
        move3a : "-Thunderbolt",
        move4a : "-Bulldoze",

        nameb : "Ampharos",
        levelb : "LV: 54",
        typeb : "Type: Electric",
        abilityb: "Ability: N/A",
        itemb : "Item: None",
        hpb : "HP: 195",
        atkb : "Atk: 86",
        defb : "Def: 96",
        spatkb : "Sp. Atk: 129",
        spdefb : "Sp. Def: 102",
        spdb : "Spd: 64",
        move1b : "-Dazzling Gleam",
        move2b : "-Thunder",
        move3b : "-Power Gem",
        move4b : "-Ice Punch",

        namec : "Stunfisk",
        levelc : "LV: 54",
        typec : "Type: Ground/Electric",
        abilityc: "Ability: N/A",
        itemc : "Item: None",
        hpc : "HP: 215",
        atkc : "Atk: 76",
        defc : "Def: 95",
        spatkc : "Sp. Atk: 92",
        spdefc : "Sp. Def: 111",
        spdc : "Spd: 39",
        move1c : "-Discharge",
        move2c : "-Thunder Shock",
        move3c : "-Stealth Rock",
        move4c : "-Mud Shot",

        named : "Mega Eelektross",
        leveld : "LV: 55",
        typed : "Type: Electric",
        abilityd: "Ability: N/A",
        itemd : "Item: Eelektrossite",
        hpd : "HP: 201",
        atkd : "Atk: 172",
        defd : "Def: 101",
        spatkd : "Sp. Atk: 161",
        spdefd : "Sp. Def: 112",
        spdd : "Spd: 101",
        move1d : "-Liquidation",
        move2d : "-Thunderbolt",
        move3d : "-Zap Cannon",
        move4d : "-Giga Drain",
    },

    {
        namea : "Heracross",
        levela : "LV: 53",
        typea : "Type: Bug/Fighting",
        abilitya: "Ability: N/A",
        itema : "Item: None",
        hpa : "HP: 181",
        atka : "Atk: 137",
        defa : "Def: 84",
        spatka : "Sp. Atk: 47",
        spdefa : "Sp. Def: 105",
        spda : "Spd: 95",
        move1a : "-Rock Blast",
        move2a : "-Pin Missile",
        move3a : "-Aerial Ace",
        move4a : "-Brick Break",

        nameb : "Medicham",
        levelb : "LV: 54",
        typeb : "Type: Fighting/Psychic",
        abilityb: "Ability: N/A",
        itemb : "Item: None",
        hpb : "HP: 162",
        atkb : "Atk: U/A",
        defb : "Def: 86",
        spatkb : "Sp. Atk: 69",
        spdefb : "Sp. Def: 86",
        spdb : "Spd: 91",
        move1b : "-Zen Headbutt",
        move2b : "-Rock Smash",
        move3b : "-Protect",
        move4b : "-Ice Punch",

        namec : "Machamp",
        levelc : "LV: 54",
        typec : "Type: Fighting",
        abilityc: "Ability: N/A",
        itemc : "Item: None",
        hpc : "HP: 195",
        atkc : "Atk: 145",
        defc : "Def: 91",
        spatkc : "Sp. Atk: 75",
        spdefc : "Sp. Def: 96",
        spdc : "Spd: 64",
        move1c : "-Bulldoze",
        move2c : "-Brick Break",
        move3c : "-Bulk Up",
        move4c : "-Brutal Swing",

        named : "Mega Falinks",
        leveld : "LV: 55",
        typed : "Type: Fighting",
        abilityd: "Ability: N/A",
        itemd : "Item: Falinksite",
        hpd : "HP: 179",
        atkd : "Atk: 161",
        defd : "Def: 161",
        spatkd : "Sp. Atk: 90",
        spdefd : "Sp. Def: 84",
        spdd : "Spd: 123",
        move1d : "-Iron Head",
        move2d : "-No Retreat",
        move3d : "-Rock Slide",
        move4d : "-Close Combat",
    },

    {
        namea : "Arbok",
        levela : "LV: 54",
        typea : "Type: Poison",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 162",
        atka : "Atk: 107",
        defa : "Def: 79",
        spatka : "Sp. Atk: 75",
        spdefa : "Sp. Def: 90",
        spda : "Spd: 91",
        move1a : "-Poison Jab",
        move2a : "-Toxic",
        move3a : "-Fire Fang",
        move4a : "-Leech Life",

        nameb : "Gyarados",
        levelb : "LV: 55",
        typeb : "Type: Water/Flying",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 204",
        atkb : "Atk: 142",
        defb : "Def: 91",
        spatkb : "Sp. Atk: 71",
        spdefb : "Sp. Def: 115",
        spdb : "Spd: 94",
        move1b : "-Waterfall",
        move2b : "-Bounce",
        move3b : "-Dragon Rush",
        move4b : "-Crunch",

        namec : "Roserade",
        levelc : "LV: 55",
        typec : "Type: Grass/Poison",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 165",
        atkc : "Atk: 82",
        defc : "Def: 76",
        spatkc : "Sp. Atk: 142",
        spdefc : "Sp. Def: 120",
        spdc : "Spd: 104",
        move1c : "-Giga Drain",
        move2c : "-Sludge Bomb",
        move3c : "-Synthesis",
        move4c : "-Shadow Ball",

        named : "Mega Scolipede",
        leveld : "LV: 56",
        typed : "Type: Bug/Poison",
        abilityd: "Ability: ",
        itemd : "Item: Scolipite",
        hpd : "HP: 176",
        atkd : "Atk: 170",
        defd : "Def: 180",
        spatkd : "Sp. Atk: 97",
        spdefd : "Sp. Def: 124",
        spdd : "Spd: 82",
        move1d : "-X-Scissor",
        move2d : "-Gunk Shot",
        move3d : "-Protect",
        move4d : "-Earthquake",
    },

    {
        namea : "Carbink",
        levela : "LV: 57",
        typea : "Type: Rock/Fairy",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 159",
        atka : "Atk: 62",
        defa : "Def: 176",
        spatka : "Sp. Atk: 62",
        spdefa : "Sp. Def: 176",
        spda : "Spd: 62",
        move1a : "-Stealth Rock",
        move2a : "-Stone Edge",
        move3a : "-Moonblast",
        move4a : "-Flash Cannon",

        nameb : "Mawile",
        levelb : "LV: 58",
        typeb : "Type: Steel/Fairy",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 162",
        atkb : "Atk: U/A",
        defb : "Def: 103",
        spatkb : "Sp. Atk: 68",
        spdefb : "Sp. Def: 68",
        spdb : "Spd: 63",
        move1b : "-Play Rough",
        move2b : "-Iron Head",
        move3b : "-Crunch",
        move4b : "-Fire Fang",

        namec : "Aurorus",
        levelc : "LV: 58",
        typec : "Type: Rock/Ice",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 247",
        atkc : "Atk: 94",
        defc : "Def: 88",
        spatkc : "Sp. Atk: 119",
        spdefc : "Sp. Def: 111",
        spdc : "Spd: 72",
        move1c : "-Blizzard",
        move2c : "-Freeze-Dry",
        move3c : "-Rock Blast",
        move4c : "-Protect",

        named : "Gardevoir",
        leveld : "LV: 58",
        typed : "Type: Psychic/Fairy",
        abilityd: "Ability: ",
        itemd : "Item: None",
        hpd : "HP: 183",
        atkd : "Atk: 80",
        defd : "Def: 80",
        spatkd : "Sp. Atk: 150",
        spdefd : "Sp. Def: 138",
        spdd : "Spd: 97",
        move1d : "-Psychic",
        move2d : "-Calm Mind",
        move3d : "-Mystical Fire",
        move4d : "-Moonblast",

        namee : "Mega Clefable",
        levele : "LV: 59",
        typee : "Type: Fairy/Flying",
        abilitye: "Ability: ",
        iteme : "Item: Clefablite",
        hpe : "HP: 227",
        atke : "Atk: 108",
        defe : "Def: 123",
        spatke : "Sp. Atk: 173",
        spdefe : "Sp. Def: 143",
        spde : "Spd: 96",
        move1e : "-Moonblast",
        move2e : "-Air Slash",
        move3e : "-Protect",
        move4e : "-Mystical Fire",
    },

    {
        namea : "Steelix",
        levela : "LV: 56",
        typea : "Type: Steel/Ground",
        abilitya: "Ability: N/A",
        itema : "Item: None",
        hpa : "HP: 185",
        atka : "Atk: 100",
        defa : "Def: 229",
        spatka : "Sp. Atk: 66",
        spdefa : "Sp. Def: 77",
        spda : "Spd: 38",
        move1a : "-Stealth Rock",
        move2a : "-Heavy Slam",
        move3a : "-Stone Edge",
        move4a : "-Breaking Swipe",

        nameb : "Scizor",
        levelb : "LV: 56",
        typeb : "Type: Bug/Steel",
        abilityb: "Ability: N/A",
        itemb : "Item: None",
        hpb : "HP: 179",
        atkb : "Atk: 150",
        defb : "Def: 117",
        spatkb : "Sp. Atk: 66",
        spdefb : "Sp. Def: 94",
        spdb : "Spd: 77",
        move1b : "-X-Scissor",
        move2b : "-Air Slash",
        move3b : "-Iron Head",
        move4b : "-Protect",

        namec : "Aggron",
        levelc : "LV: 56",
        typec : "Type: Steel/Rock",
        abilityc: "Ability: N/A",
        itemc : "Item: None",
        hpc : "HP: 179",
        atkc : "Atk: 128",
        defc : "Def: 206",
        spatkc : "Sp. Atk: 72",
        spdefc : "Sp. Def: 72",
        spdc : "Spd: 61",
        move1c : "-Iron Tail",
        move2c : "-Rock Slide",
        move3c : "-Earthquake",
        move4c : "-Ice Punch",

        named : "Mega Skarmory",
        leveld : "LV: 57",
        typed : "Type: Steel/Flying",
        abilityd: "Ability: N/A",
        itemd : "Item: Skarmorite",
        hpd : "HP: 185",
        atkd : "Atk: 173",
        defd : "Def: 138",
        spatkd : "Sp. Atk: 59",
        spdefd : "Sp. Def: 127",
        spdd : "Spd: 138",
        move1d : "-Steel Wing",
        move2d : "-Drill Run",
        move3d : "-Night Slash",
        move4d : "-Protect",
    },

    {
        namea : "Ampharos",
        levela : "LV: 57",
        typea : "Type: Electric",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 169",
        atka : "Atk: 90",
        defa : "Def: 101",
        spatka : "Sp. Atk: 136",
        spdefa : "Sp. Def: 107",
        spda : "Spd: 67",
        move1a : "-Thunder",
        move2a : "-Dragon Pulse",
        move3a : "-Power Gem",
        move4a : "-Light Screen",

        nameb : "Mawile",
        levelb : "LV: 57",
        typeb : "Type: Steel/Fairy",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 124",
        atkb : "Atk: U/A",
        defb : "Def: 101",
        spatkb : "Sp. Atk: 67",
        spdefb : "Sp. Def: 67",
        spdb : "Spd: 62",
        move1b : "-Play Rough",
        move2b : "-Iron Head",
        move3b : "-Dynamic Punch",
        move4b : "-Crunch",

        namec : "Lopunny",
        levelc : "LV: 57",
        typec : "Type: Normal",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 141",
        atkc : "Atk: 91",
        defc : "Def: 100",
        spatkc : "Sp. Atk: 66",
        spdefc : "Sp. Def: 114",
        spdc : "Spd: 124",
        move1c : "-Power-Up Punch",
        move2c : "-Fire Punch",
        move3c : "-Ice Punch",
        move4c : "-Thunder Punch",

        named : "Lucario",
        leveld : "LV: 57",
        typed : "Type: Fighting/Steel",
        abilityd: "Ability: ",
        itemd : "Item: None",
        hpd : "HP: 146",
        atkd : "Atk: 130",
        defd : "Def: 84",
        spatkd : "Sp. Atk: 136",
        spdefd : "Sp. Def: 84",
        spdd : "Spd: 107",
        move1d : "-Aura Sphere",
        move2d : "-Flash Cannon",
        move3d : "-Calm Mind",
        move4d : "-Psychic",

        namee : "Mega Malamar",
        levele : "LV: 58",
        typee : "Type: Dark/Psychic",
        abilitye: "Ability: ",
        iteme : "Item: Malamarite",
        hpe : "HP: 213",
        atke : "Atk: 132",
        defe : "Def: 115",
        spatke : "Sp. Atk: 127",
        spdefe : "Sp. Def: 152",
        spde : "Spd: 115",
        move1e : "-Night Slash",
        move2e : "-Psycho Cut",
        move3e : "-Poison Jab",
        move4e : "-Slash",
    },

    {
        namea : "Talonflame",
        levela : "LV: 59",
        typea : "Type: Fire/Flying",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 207",
        atka : "Atk: 109",
        defa : "Def: 97",
        spatka : "Sp. Atk: 101",
        spdefa : "Sp. Def: 95",
        spda : "Spd: 162",
        move1a : "-Flare Blitz",
        move2a : "-Steel Wing",
        move3a : "-Quick Attack",
        move4a : "-U-Turn",

        nameb : "Camerupt",
        levelb : "LV: 59",
        typeb : "Type: Fire/Ground",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 197",
        atkb : "Atk: 131",
        defb : "Def: 96",
        spatkb : "Sp. Atk: 137",
        spdefb : "Sp. Def: 102",
        spdb : "Spd: 61",
        move1b : "-Lava Plume",
        move2b : "-Earthquake",
        move3b : "-Rock Slide",
        move4b : "-Protect",

        namec : "Aerodactyl",
        levelc : "LV: 60",
        typec : "Type: Rock/Flying",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 212",
        atkc : "Atk: 140",
        defc : "Def: 92",
        spatkc : "Sp. Atk: 86",
        spdefc : "Sp. Def: 104",
        spdc : "Spd: 170",
        move1c : "-Stone Edge",
        move2c : "-Iron Head",
        move3c : "-Crunch",
        move4c : "-Thunder Fang",

        named : "Metagross",
        leveld : "LV: 60",
        typed : "Type: Steel/Psychic",
        abilityd: "Ability: ",
        itemd : "Item: None",
        hpd : "HP: 212",
        atkd : "Atk: 176",
        defd : "Def: 170",
        spatkd : "Sp. Atk: 128",
        spdefd : "Sp. Def: 122",
        spdd : "Spd: 98",
        move1d : "-Bullet Punch",
        move2d : "-Psycho Cut",
        move3d : "-Brutal Swing",
        move4d : "-Ice Punch",

        namee : "Mega Pyroar",
        levele : "LV: 61",
        typee : "Type: Fire/Normal",
        abilitye: "Ability: ",
        iteme : "Item: None",
        hpe : "HP: 223",
        atke : "Atk: 121",
        defe : "Def: 126",
        spatke : "Sp. Atk: 171",
        spdefe : "Sp. Def: 119",
        spde : "Spd: 167",
        move1e : "-Flamethrower",
        move2e : "-Hyper Voice",
        move3e : "-Earth Power",
        move4e : "-Snarl",
    },

    {
        namea : "Pangoro",
        levela : "LV: 61",
        typea : "Type: Fighting/Dark",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 234",
        atka : "Atk: 165",
        defa : "Def: 109",
        spatka : "Sp. Atk: 98",
        spdefa : "Sp. Def: 100",
        spda : "Spd: 84",
        move1a : "-Brick Break",
        move2a : "-Crunch",
        move3a : "-Bullet Punch",
        move4a : "-Protect",

        nameb : "Malamar",
        levelb : "LV: 61",
        typeb : "Type: Dark/Psychic",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 223",
        atkb : "Atk: 126",
        defb : "Def: 121",
        spatkb : "Sp. Atk: 97",
        spdefb : "Sp. Def: 105",
        spdb : "Spd: 103",
        move1b : "-Hypnosis",
        move2b : "-Psyshock",
        move3b : "-Night Slash",
        move4b : "-Liquidation",

        namec : "Pyroar",
        levelc : "LV: 61",
        typec : "Type: Fire/Normal",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 223",
        atkc : "Atk: 97",
        defc : "Def: 101",
        spatkc : "Sp. Atk: 147",
        spdefc : "Sp. Def: 94",
        spdc : "Spd: 143",
        move1c : "-Overheat",
        move2c : "-Hyper Voice",
        move3c : "-Earth Power",
        move4c : "-Snarl",

        named : "Tyranitar",
        leveld : "LV: 62",
        typed : "Type: Rock/Dark",
        abilityd: "Ability: ",
        itemd : "Item: None",
        hpd : "HP: 244",
        atkd : "Atk: 180",
        defd : "Def: 150",
        spatkd : "Sp. Atk: 132",
        spdefd : "Sp. Def: 138",
        spdd : "Spd: 89",
        move1d : "-Stone Edge",
        move2d : "-Crunch",
        move3d : "-Earthquake",
        move4d : "-Ice Punch",

        namee : "Salamence",
        levele : "LV: 62",
        typee : "Type: Dragon/Flying",
        abilitye: "Ability: ",
        iteme : "Item: None",
        hpe : "HP: 238",
        atke : "Atk: 181",
        defe : "Def: 113",
        spatke : "Sp. Atk: 150",
        spdefe : "Sp. Def: 113",
        spde : "Spd: 138",
        move1e : "-Draco Meteor",
        move2e : "-Air Slash",
        move3e : "-Fire Fang",
        move4e : "-Earthquake",

        namef : "Mega Charizard X",
        levelf : "LV: 63",
        typef : "Type: Fire/Dragon",
        abilityf: "Ability: ",
        itemf : "Item: Charizardite X",
        hpf : "HP: 229",
        atkf : "Atk: 187",
        deff : "Def: 163",
        spatkf : "Sp. Atk: 187",
        spdeff : "Sp. Def: 131",
        spdf : "Spd: 149",
        move1f : "-Flare Blitz",
        move2f : "-Dragon Rush",
        move3f : "-Air Slash",
        move4f : "-Protect",
    },

    {
        namea : "Meowstic",
        levela : "LV: 62",
        typea : "Type: Psychic",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 202",
        atka : "Atk: 64",
        defa : "Def: 99",
        spatka : "Sp. Atk: 107",
        spdefa : "Sp. Def: 105",
        spda : "Spd: 133",
        move1a : "-Reflect",
        move2a : "-Light Screen",
        move3a : "-Psychic",
        move4a : "-Thunderbolt",

        nameb : "Goodra",
        levelb : "LV: 62",
        typeb : "Type: Dragon",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 231",
        atkb : "Atk: 138",
        defb : "Def: 101",
        spatkb : "Sp. Atk: 150",
        spdefb : "Sp. Def: 200",
        spdb : "Spd: 113",
        move1b : "-Toxic",
        move2b : "-Surf",
        move3b : "-Draco Meteor",
        move4b : "-Blizzard",

        namec : "Avalugg",
        levelc : "LV: 62",
        typec : "Type: Ice",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 238",
        atkc : "Atk: 159",
        defc : "Def: 242",
        spatkc : "Sp. Atk: 68",
        spdefc : "Sp. Def: 71",
        spdc : "Spd: 49",
        move1c : "-Protect",
        move2c : "-Icicle Crash",
        move3c : "-Stone Edge",
        move4c : "-Crunch",

        named : "Emboar",
        leveld : "LV: 63",
        typed : "Type: Fire/Fighting",
        abilityd: "Ability: ",
        itemd : "Item: None",
        hpd : "HP: 251",
        atkd : "Atk: 159",
        defd : "Def: 86",
        spatkd : "Sp. Atk: 131",
        spdefd : "Sp. Def: 86",
        spdd : "Spd: 86",
        move1d : "-Flare Blitz",
        move2d : "-Bulk Up",
        move3d : "-Stone Edge",
        move4d : "-Thunder Punch",

        namee : "Manectric",
        levele : "LV: 63",
        typee : "Type: Electric",
        abilitye: "Ability: ",
        iteme : "Item: None",
        hpe : "HP: 200",
        atke : "Atk: 99",
        defe : "Def: 80",
        spatke : "Sp. Atk: 137",
        spdefe : "Sp. Def: 80",
        spde : "Spd: 137",
        move1e : "-Thunder",
        move2e : "-Overheat",
        move3e : "-Snarl",
        move4e : "-Protect",

        namef : "Mega Meganium",
        levelf : "LV: 64",
        typef : "Type: Grass/Fairy",
        abilityf: "Ability: ",
        itemf : "Item: Meganiumite",
        hpf : "HP: 216",
        atkf : "Atk: 122",
        deff : "Def: 152",
        spatkf : "Sp. Atk: 188",
        spdeff : "Sp. Def: 152",
        spdf : "Spd: 107",
        move1f : "-Giga Drain",
        move2f : "-Leech Seed",
        move3f : "-Earth Power",
        move4f : "-Dazzling Gleam",
    },

    {
        namea : "Meowstic",
        levela : "LV: 62",
        typea : "Type: Psychic",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 202",
        atka : "Atk: 64",
        defa : "Def: 99",
        spatka : "Sp. Atk: 107",
        spdefa : "Sp. Def: 105",
        spda : "Spd: 133",
        move1a : "-Reflect",
        move2a : "-Light Screen",
        move3a : "-Psychic",
        move4a : "-Thunderbolt",

        nameb : "Goodra",
        levelb : "LV: 62",
        typeb : "Type: Dragon",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 231",
        atkb : "Atk: 138",
        defb : "Def: 101",
        spatkb : "Sp. Atk: 150",
        spdefb : "Sp. Def: 200",
        spdb : "Spd: 113",
        move1b : "-Toxic",
        move2b : "-Surf",
        move3b : "-Draco Meteor",
        move4b : "-Blizzard",

        namec : "Avalugg",
        levelc : "LV: 62",
        typec : "Type: Ice",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 238",
        atkc : "Atk: 159",
        defc : "Def: 242",
        spatkc : "Sp. Atk: 68",
        spdefc : "Sp. Def: 71",
        spdc : "Spd: 49",
        move1c : "-Protect",
        move2c : "-Icicle Crash",
        move3c : "-Stone Edge",
        move4c : "-Crunch",

        named : "Feraligatr",
        leveld : "LV: 63",
        typed : "Type: Water",
        abilityd: "Ability: ",
        itemd : "Item: None",
        hpd : "HP: 219",
        atkd : "Atk: 137",
        defd : "Def: 131",
        spatkd : "Sp. Atk: 103",
        spdefd : "Sp. Def: 109",
        spdd : "Spd: 103",
        move1d : "-Liquidation",
        move2d : "-Breaking Swipe",
        move3d : "-Ice Fang",
        move4d : "-Bulldoze",

        namee : "Manectric",
        levele : "LV: 63",
        typee : "Type: Electric",
        abilitye: "Ability: ",
        iteme : "Item: None",
        hpe : "HP: 200",
        atke : "Atk: 99",
        defe : "Def: 80",
        spatke : "Sp. Atk: 137",
        spdefe : "Sp. Def: 80",
        spde : "Spd: 137",
        move1e : "-Thunder",
        move2e : "-Overheat",
        move3e : "-Snarl",
        move4e : "-Protect",

        namef : "Mega Emboar",
        levelf : "LV: 64",
        typef : "Type: Fire/Fighting",
        abilityf: "Ability: ",
        itemf : "Item: Emboarite",
        hpf : "HP: 255",
        atkf : "Atk: 194",
        deff : "Def: 101",
        spatkf : "Sp. Atk: 145",
        spdeff : "Sp. Def: 145",
        spdf : "Spd: 101",
        move1f : "-Flare Blitz",
        move2f : "-Bulk Up",
        move3f : "-Stone Edge",
        move4f : "-Thunder Punch",
    },

    {
        namea : "Meowstic",
        levela : "LV: 62",
        typea : "Type: Psychic",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 202",
        atka : "Atk: 64",
        defa : "Def: 99",
        spatka : "Sp. Atk: 107",
        spdefa : "Sp. Def: 105",
        spda : "Spd: 133",
        move1a : "-Reflect",
        move2a : "-Light Screen",
        move3a : "-Psychic",
        move4a : "-Thunderbolt",

        nameb : "Goodra",
        levelb : "LV: 62",
        typeb : "Type: Dragon",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 231",
        atkb : "Atk: 138",
        defb : "Def: 101",
        spatkb : "Sp. Atk: 150",
        spdefb : "Sp. Def: 200",
        spdb : "Spd: 113",
        move1b : "-Toxic",
        move2b : "-Surf",
        move3b : "-Draco Meteor",
        move4b : "-Blizzard",

        namec : "Avalugg",
        levelc : "LV: 62",
        typec : "Type: Ice",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 238",
        atkc : "Atk: 159",
        defc : "Def: 242",
        spatkc : "Sp. Atk: 68",
        spdefc : "Sp. Def: 71",
        spdc : "Spd: 49",
        move1c : "-Protect",
        move2c : "-Icicle Crash",
        move3c : "-Stone Edge",
        move4c : "-Crunch",

        named : "Meganium",
        leveld : "LV: 63",
        typed : "Type: Grass",
        abilityd: "Ability: ",
        itemd : "Item: None",
        hpd : "HP: 213",
        atkd : "Atk: 108",
        defd : "Def: 131",
        spatkd : "Sp. Atk: 109",
        spdefd : "Sp. Def: 131",
        spdd : "Spd: 105",
        move1d : "-Giga Drain",
        move2d : "-Leech Seed",
        move3d : "-Earth Power",
        move4d : "-Dazzling Gleam",

        namee : "Manectric",
        levele : "LV: 63",
        typee : "Type: Electric",
        abilitye: "Ability: ",
        iteme : "Item: None",
        hpe : "HP: 200",
        atke : "Atk: 99",
        defe : "Def: 80",
        spatke : "Sp. Atk: 137",
        spdefe : "Sp. Def: 80",
        spde : "Spd: 137",
        move1e : "-Thunder",
        move2e : "-Overheat",
        move3e : "-Snarl",
        move4e : "-Protect",

        namef : "Mega Feraligatr",
        levelf : "LV: 64",
        typef : "Type: Water/Dragon",
        abilityf: "Ability: ",
        itemf : "Item: Feraligite",
        hpf : "HP: 223",
        atkf : "Atk: 209",
        deff : "Def: 165",
        spatkf : "Sp. Atk: 118",
        spdeff : "Sp. Def: 124",
        spdf : "Spd: 104",
        move1f : "-Liquidation",
        move2f : "-Breaking Swipe",
        move3f : "-Ice Fang",
        move4f : "-Bulldoze",
    },

    {
        namea : "Pyroar",
        levela : "LV: 78",
        typea : "Type: Fire/Normal",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: 283",
        atka : "Atk: 122",
        defa : "Def: 129",
        spatka : "Sp. Atk: 186",
        spdefa : "Sp. Def: 119",
        spda : "Spd: 182",
        move1a : "-Flamethrower",
        move2a : "-Hyper Voice",
        move3a : "-Snarl",
        move4a : "-Solar Beam",

        nameb : "Florges",
        levelb : "LV: 78",
        typeb : "Type: Fairy",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: 270",
        atkb : "Atk: 118",
        defb : "Def: 122",
        spatkb : "Sp. Atk: 191",
        spdefb : "Sp. Def: 256",
        spdb : "Spd: 133",
        move1b : "-Calm Mind",
        move2b : "-Dazzling Gleam",
        move3b : "-Psychic",
        move4b : "-Energy Ball",

        namec : "Sableye",
        levelc : "LV: 78",
        typec : "Type: Dark/Ghost",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: 226",
        atkc : "Atk: 133",
        defc : "Def: 133",
        spatkc : "Sp. Atk: 118",
        spdefc : "Sp. Def: 118",
        spdc : "Spd: 94",
        move1c : "-Will-O-Wisp",
        move2c : "-Confuse Ray",
        move3c : "-Shadow Ball",
        move4c : "-Night Slash",

        named : "Noivern",
        leveld : "LV: 79",
        typed : "Type: Flying/Dragon",
        abilityd: "Ability: ",
        itemd : "Item: None",
        hpd : "HP: 284",
        atkd : "Atk: 127",
        defd : "Def: 143",
        spatkd : "Sp. Atk: 170",
        spdefd : "Sp. Def: 143",
        spdd : "Spd: 211",
        move1d : "-Boomburst",
        move2d : "-Super Fang",
        move3d : "-Dragon Pulse",
        move4d : "-Hurricane",

        namee : "Garbodor",
        levele : "LV: 79",
        typee : "Type: Poison",
        abilitye: "Ability: ",
        iteme : "Item: None",
        hpe : "HP: 277",
        atke : "Atk: 166",
        defe : "Def: 146",
        spatke : "Sp. Atk: 111",
        spdefe : "Sp. Def: 146",
        spde : "Spd: 135",
        move1e : "-Gunk Shot",
        move2e : "-Brutal Swing",
        move3e : "-Rock Blast",
        move4e : "-Metal Claw",

        namef : "Mega Gyarados",
        levelf : "LV: 80",
        typef : "Type: Water/Dark",
        abilityf: "Ability: ",
        itemf : "Item: Gyaradosite",
        hpf : "HP: 316",
        atkf : "Atk: 277",
        deff : "Def: 203",
        spatkf : "Sp. Atk: 141",
        spdeff : "Sp. Def: 237",
        spdf : "Spd: 158",
        move1f : "-Waterfall",
        move2f : "-Crunch",
        move3f : "-Ice Fang",
        move4f : "-Earthquake",
    },

]

function displayZATrainers() {
    let newTrainerId = this.id;
    if (newTrainerId !== currentTrainerId) {
        currentTrainerId = newTrainerId;
        showZAImages(newTrainerId);
        showPokemonZAImages(newTrainerId);
    }

    let zaTrainer = this.dataset.member;

    document.querySelector('#name1').textContent = za_trainers [zaTrainer].namea;
    document.querySelector('#level1').textContent = za_trainers [zaTrainer].levela;
    document.querySelector('#type1').textContent = za_trainers [zaTrainer].typea;
    document.querySelector('#ability1').textContent= za_trainers [zaTrainer].abilitya;
    document.querySelector('#item1').textContent = za_trainers [zaTrainer].itema;
    document.querySelector('#hp1').textContent = za_trainers [zaTrainer].hpa;
    document.querySelector('#atk1').textContent = za_trainers [zaTrainer].atka;
    document.querySelector('#def1').textContent = za_trainers [zaTrainer].defa;
    document.querySelector('#spatk1').textContent = za_trainers [zaTrainer].spatka;
    document.querySelector('#spdef1').textContent = za_trainers [zaTrainer].spdefa;
    document.querySelector('#spd1').textContent = za_trainers [zaTrainer].spda;
    document.querySelector('#move1_1').textContent = za_trainers [zaTrainer].move1a;
    document.querySelector('#move2_1').textContent = za_trainers [zaTrainer].move2a;
    document.querySelector('#move3_1').textContent = za_trainers [zaTrainer].move3a;
    document.querySelector('#move4_1').textContent = za_trainers [zaTrainer].move4a;

    
    document.querySelector('#name2').textContent = za_trainers [zaTrainer].nameb;
    document.querySelector('#level2').textContent = za_trainers [zaTrainer].levelb;
    document.querySelector('#type2').textContent = za_trainers [zaTrainer].typeb;
    document.querySelector('#ability2').textContent= za_trainers [zaTrainer].abilityb;
    document.querySelector('#item2').textContent = za_trainers [zaTrainer].itemb;
    document.querySelector('#hp2').textContent = za_trainers [zaTrainer].hpb;
    document.querySelector('#atk2').textContent = za_trainers [zaTrainer].atkb;
    document.querySelector('#def2').textContent = za_trainers [zaTrainer].defb;
    document.querySelector('#spatk2').textContent = za_trainers [zaTrainer].spatkb;
    document.querySelector('#spdef2').textContent = za_trainers [zaTrainer].spdefb;
    document.querySelector('#spd2').textContent = za_trainers [zaTrainer].spdb;
    document.querySelector('#move1_2').textContent = za_trainers [zaTrainer].move1b;
    document.querySelector('#move2_2').textContent = za_trainers [zaTrainer].move2b;
    document.querySelector('#move3_2').textContent = za_trainers [zaTrainer].move3b;
    document.querySelector('#move4_2').textContent = za_trainers [zaTrainer].move4b;

    document.querySelector('#name3').textContent = za_trainers [zaTrainer].namec;
    document.querySelector('#level3').textContent = za_trainers [zaTrainer].levelc;
    document.querySelector('#type3').textContent = za_trainers [zaTrainer].typec;
    document.querySelector('#ability3').textContent= za_trainers [zaTrainer].abilityc;
    document.querySelector('#item3').textContent = za_trainers [zaTrainer].itemc;
    document.querySelector('#hp3').textContent = za_trainers [zaTrainer].hpc;
    document.querySelector('#atk3').textContent = za_trainers [zaTrainer].atkc;
    document.querySelector('#def3').textContent = za_trainers [zaTrainer].defc;
    document.querySelector('#spatk3').textContent = za_trainers [zaTrainer].spatkc;
    document.querySelector('#spdef3').textContent = za_trainers [zaTrainer].spdefc;
    document.querySelector('#spd3').textContent = za_trainers [zaTrainer].spdc;
    document.querySelector('#move1_3').textContent = za_trainers [zaTrainer].move1c;
    document.querySelector('#move2_3').textContent = za_trainers [zaTrainer].move2c;
    document.querySelector('#move3_3').textContent = za_trainers [zaTrainer].move3c;
    document.querySelector('#move4_3').textContent = za_trainers [zaTrainer].move4c;

    document.querySelector('#name4').textContent = za_trainers [zaTrainer].named;
    document.querySelector('#level4').textContent = za_trainers [zaTrainer].leveld;
    document.querySelector('#type4').textContent = za_trainers [zaTrainer].typed;
    document.querySelector('#ability4').textContent= za_trainers [zaTrainer].abilityd;
    document.querySelector('#item4').textContent = za_trainers [zaTrainer].itemd;
    document.querySelector('#hp4').textContent = za_trainers [zaTrainer].hpd;
    document.querySelector('#atk4').textContent = za_trainers [zaTrainer].atkd;
    document.querySelector('#def4').textContent = za_trainers [zaTrainer].defd;
    document.querySelector('#spatk4').textContent = za_trainers [zaTrainer].spatkd;
    document.querySelector('#spdef4').textContent = za_trainers [zaTrainer].spdefd;
    document.querySelector('#spd4').textContent = za_trainers [zaTrainer].spdd;
    document.querySelector('#move1_4').textContent = za_trainers [zaTrainer].move1d;
    document.querySelector('#move2_4').textContent = za_trainers [zaTrainer].move2d;
    document.querySelector('#move3_4').textContent = za_trainers [zaTrainer].move3d;
    document.querySelector('#move4_4').textContent = za_trainers [zaTrainer].move4d;

    document.querySelector('#name5').textContent = za_trainers [zaTrainer].namee;
    document.querySelector('#level5').textContent = za_trainers [zaTrainer].levele;
    document.querySelector('#type5').textContent = za_trainers [zaTrainer].typee;
    document.querySelector('#ability5').textContent= za_trainers [zaTrainer].abilitye;
    document.querySelector('#item5').textContent = za_trainers [zaTrainer].iteme;
    document.querySelector('#hp5').textContent = za_trainers [zaTrainer].hpe;
    document.querySelector('#atk5').textContent = za_trainers [zaTrainer].atke;
    document.querySelector('#def5').textContent = za_trainers [zaTrainer].defe;
    document.querySelector('#spatk5').textContent = za_trainers [zaTrainer].spatke;
    document.querySelector('#spdef5').textContent = za_trainers [zaTrainer].spdefe;
    document.querySelector('#spd5').textContent = za_trainers [zaTrainer].spde;
    document.querySelector('#move1_5').textContent = za_trainers [zaTrainer].move1e;
    document.querySelector('#move2_5').textContent = za_trainers [zaTrainer].move2e;
    document.querySelector('#move3_5').textContent = za_trainers [zaTrainer].move3e;
    document.querySelector('#move4_5').textContent = za_trainers [zaTrainer].move4e;

    document.querySelector('#name6').textContent = za_trainers [zaTrainer].namef;
    document.querySelector('#level6').textContent = za_trainers [zaTrainer].levelf;
    document.querySelector('#type6').textContent = za_trainers [zaTrainer].typef;
    document.querySelector('#ability6').textContent= za_trainers [zaTrainer].abilityf;
    document.querySelector('#item6').textContent = za_trainers [zaTrainer].itemf;
    document.querySelector('#hp6').textContent = za_trainers [zaTrainer].hpf;
    document.querySelector('#atk6').textContent = za_trainers [zaTrainer].atkf;
    document.querySelector('#def6').textContent = za_trainers [zaTrainer].deff;
    document.querySelector('#spatk6').textContent = za_trainers [zaTrainer].spatkf;
    document.querySelector('#spdef6').textContent = za_trainers [zaTrainer].spdeff;
    document.querySelector('#spd6').textContent = za_trainers [zaTrainer].spdf;
    document.querySelector('#move1_6').textContent = za_trainers [zaTrainer].move1f;
    document.querySelector('#move2_6').textContent = za_trainers [zaTrainer].move2f;
    document.querySelector('#move3_6').textContent = za_trainers [zaTrainer].move3f;
    document.querySelector('#move4_6').textContent = za_trainers [zaTrainer].move4f;
}

function showZAImages(trainerId) {
    var trainerPicture = document.querySelector("#trainer_image");
    
    trainerPicture.innerHTML = "";

    var imgTrainer = document.createElement("img");
    imgTrainer.src = "images/trainer_data_images/trainers/za/" + trainerId + ".png";
    imgTrainer.setAttribute("alt", `Image of ${trainerId}`)
    trainerPicture.appendChild(imgTrainer);
}

function showPokemonZAImages(trainerId) {
    var pokemon1Picture = document.querySelector("#pokemon_1_image");
    var pokemon2Picture = document.querySelector("#pokemon_2_image");
    var pokemon3Picture = document.querySelector("#pokemon_3_image");
    var pokemon4Picture = document.querySelector("#pokemon_4_image");
    var pokemon5Picture = document.querySelector("#pokemon_5_image");
    var pokemon6Picture = document.querySelector("#pokemon_6_image");
    var imgPokemon1 = document.createElement("img");
    var imgPokemon2 = document.createElement("img");
    var imgPokemon3 = document.createElement("img");
    var imgPokemon4 = document.createElement("img");
    var imgPokemon5 = document.createElement("img");
    var imgPokemon6 = document.createElement("img");
    
    pokemon1Picture.innerHTML = "";
    pokemon2Picture.innerHTML = "";
    pokemon3Picture.innerHTML = "";
    pokemon4Picture.innerHTML = "";
    pokemon5Picture.innerHTML = "";
    pokemon6Picture.innerHTML = "";

    
    imgPokemon1.src = "images/trainer_data_images/pokemon/za/" + trainerId + "_1.png";
    imgPokemon2.src = "images/trainer_data_images/pokemon/za/" + trainerId + "_2.png";
    imgPokemon3.src = "images/trainer_data_images/pokemon/za/" + trainerId + "_3.png";
    imgPokemon4.src = "images/trainer_data_images/pokemon/za/" + trainerId + "_4.png";
    imgPokemon5.src = "images/trainer_data_images/pokemon/za/" + trainerId + "_5.png";
    imgPokemon6.src = "images/trainer_data_images/pokemon/za/" + trainerId + "_6.png";
    imgPokemon1.setAttribute("alt", `Image of Pokemon 1`)
    imgPokemon2.setAttribute("alt", `Image of Pokemon 2`)
    imgPokemon3.setAttribute("alt", `Image of Pokemon 3`)
    imgPokemon4.setAttribute("alt", `Image of Pokemon 4`)
    imgPokemon5.setAttribute("alt", `Image of Pokemon 5`)
    imgPokemon6.setAttribute("alt", `Image of Pokemon 6`)

    imgPokemon1.onerror = function() {
        imgPokemon1.src = "images/trainer_data_images/pokemon/blank.png"; 
    };

    imgPokemon2.onerror = function() {
        imgPokemon2.src = "images/trainer_data_images/pokemon/blank.png";
    };

    imgPokemon3.onerror = function() {
        imgPokemon3.src = "images/trainer_data_images/pokemon/blank.png";
    };

    imgPokemon4.onerror = function() {
        imgPokemon4.src = "images/trainer_data_images/pokemon/blank.png";
    };

    imgPokemon5.onerror = function() {
        imgPokemon5.src = "images/trainer_data_images/pokemon/blank.png";
    };

    imgPokemon6.onerror = function() {
        imgPokemon6.src = "images/trainer_data_images/pokemon/blank.png";
    };

    pokemon1Picture.appendChild(imgPokemon1);
    pokemon2Picture.appendChild(imgPokemon2);
    pokemon3Picture.appendChild(imgPokemon3);
    pokemon4Picture.appendChild(imgPokemon4);
    pokemon5Picture.appendChild(imgPokemon5);
    pokemon6Picture.appendChild(imgPokemon6);

    clearDivs()

    refCredit.textContent = "Project Pokemon"
    refCredit.href = "https://github.com/projectpokemon/za-textport/blob/main/Trainers/trainers_pretty.txt"
}

vinnie.addEventListener("click", displayZATrainers)
tarragon.addEventListener("click", displayZATrainers)
canariP.addEventListener("click", displayZATrainers)
canariE.addEventListener("click", displayZATrainers)
gwynnE.addEventListener("click", displayZATrainers)
ivorP.addEventListener("click", displayZATrainers)
philippeD.addEventListener("click", displayZATrainers)
gwynnD.addEventListener("click", displayZATrainers)
corbeauP.addEventListener("click", displayZATrainers)
// lida.addEventListener("click", displayZATrainers)
naveen.addEventListener("click", displayZATrainers)
lebanne.addEventListener("click", displayZATrainers)
canariT.addEventListener("click", displayZATrainers)
ivorT.addEventListener("click", displayZATrainers)
corbeauT.addEventListener("click", displayZATrainers)
jacinthe.addEventListener("click", displayZATrainers)
philippeB.addEventListener("click", displayZATrainers)
emma.addEventListener("click", displayZATrainers)
griselle.addEventListener("click", displayZATrainers)
grisham.addEventListener("click", displayZATrainers)
urbainTaunieCM.addEventListener("click", displayZATrainers)
urbainTaunieCE.addEventListener("click", displayZATrainers)
urbainTaunieCF.addEventListener("click", displayZATrainers)
lPostgame.addEventListener("click", displayZATrainers)